config/routes.rb
Rails.application.routes.draw do
 
  resources :cryptos
  devise_for :users
  get 'home/about'
  get 'home/search'
  post "/home/search" => 'home/search'
  root 'home#index'

end

app/models/crypto.rb
class Crypto < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @url = URI(@url)
    @response = Net::HTTP.get(@url)
    @coins_search = JSON.parse(@response)
    @profit_loss = 0
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @url = URI(@url)
    @response = Net::HTTP.get(@url)
    @coins_search = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
    
  end
  


  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    
    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "Not Authorized to edit this entry" if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @url = URI(@url)
    @response = Net::HTTP.get(@url)
    @coins = JSON.parse(@response)
    @coins_arr = ["BTC", "LSK", "ETH", "ETC", "XRP"]
  end
  
  def about
  end
  
  def search
    
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @url = URI(@url)
    @response = Net::HTTP.get(@url)
    @coins_search = JSON.parse(@response)
    
    
    @symbol = params[:sym]
    @name = params[:curr_name]
   
    
    if @name
      @name = @name.capitalize
    end
    
    if @name == ""
      @name = "You forgot to type something."
    end
  end
end
    
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_for(@crypto) do |f| %>
  <% if @crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% @crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>
  <div class="field">
    <%= f.label :cost_per %><br>
    <%= f.text_field :cost_per %>
  </div>
  <div class="field">
    <%= f.label :amount_owned %><br>
    <%= f.text_field :amount_owned %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form' %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Listing Cryptos</h1>
<br />
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>

      <th>Name</th>
      <th>Current Price</th>
      <th>1h Change</th>
      <th>24h Change</th>
      <th>7 Days Change</th>
      <th>Current Value</th>
      <th>Total Paid</th>
      <th>Profit</th>
      <th>Cost Payed Per</th>
      <th>Amount Owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        <tr>
          <% for x in @coins_search %>
              <% if crypto.symbol == x["symbol"] %>
                  <td><%= link_to x["name"], crypto %></td>
                  <td><%= number_to_currency(x["price_usd"].to_d) %></td>
                  <td><%= x["percent_change_1h"] %>%</td>
                  <td><%= x["percent_change_24h"] %>%</td>
                  <td><%= x["percent_change_7d"]%>%</td>
                  <td>$<%= (x["price_usd"].to_d * crypto.amount_owned).round(2) %></td>
                  <td>$<%= (x["price_usd"].to_d * crypto.amount_owned).round(3) %></td>
                  <td><%= number_to_currency((x["price_usd"].to_d * crypto.amount_owned)- (crypto.cost_per*crypto.amount_owned)) %></td>
                  <% @profit_loss += (x["price_usd"].to_d * crypto.amount_owned) - (crypto.cost_per*crypto.amount_owned) %>
              <% end %>
          <% end %>
          <td>$<%= crypto.cost_per %></td>
          <td><%= crypto.amount_owned %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br />
<br />
<strong>Portfolio profits/losses</strong> <%= number_to_currency(@profit_loss) %>
<br />
<br />
<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-default" %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form' %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add a new cryptocurrency</h3>
  </div>
  
  <div class="panel-body">
    <p>
      <h3><%= @crypto.symbol %>()</h3>
    </p>
    
    <p>
      <strong>Cost per:</strong>
      <%= @crypto.cost_per %>
    </p>
    
    <p>
      <strong>Amount owned:</strong>
      <%= @crypto.amount_owned %>
    </p>
  </div>
  
  <div class = "panel-footer">
    <%= link_to 'Edit', edit_crypto_path(@crypto) %> |
    <%= link_to 'Delete Cryptocurrency', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', cryptos_path %>
  </div>
   </div>

app/views/home/_flash.html.erb
<% flash.each do |name, message| %>
    <div class = "alert-alert-warning alert-dismissible">
        <p><button class="close" data-dismiss="alert">
            <i class = "glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, message) %></p>
    </div>
<% end %>

app/views/home/_navbar.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cryptocurrency Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        
        <li><%= link_to "About us", home_about_path %></li>
        <li><%= link_to "Search", home_search_path %></li>
        
        
        <% if user_signed_in? %>
          <li><%= link_to "Add new crypto", new_crypto_path %></li>
          <li><%= link_to "Cryptos listing", cryptos_path %></li>
          <li><%= link_to "Edit profile", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h2>The website is under construction.</h2>

app/views/home/index.html.erb
<h3>The list of my favorites cryptocurrencies: </h3>

<% @coins %>

<% for x in @coins %>
    <% for coin in @coins_arr %>
        <% if coin == x["symbol"] %>
            <p>Rank: <%= x["rank"] %></p>
            <p><%= x["name"] %>: $<%= x["price_usd"] %></p>
        <% end %>
    <% end %>
<% end %>

<br />

app/views/home/search.html.erb
<h3> Cryptocurrency search </h3>

    <%= form_tag home_search_path, :method => 'POST' do %>
        <%= text_field_tag "curr_name", nil, placeholder: "Enter Crypto Name", size: 50 %>
        <%= submit_tag "Search Stock Quote" %>
    <% end %>
    </br>
    
    <% if @name %>
        <% for x in @coins_search %>
            <% if @name == x["name"] %>
                <p><%= x["name"] %>: $<%= x["price_usd"]%></p>
                Rank: <%= x["rank"] %>
               <% end %>
        <% end %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'home/navbar' %>
  
<div class="container">
  <%= render 'home/flash' %>
  <%= yield %>
</div>

</body>
</html>